//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetAspNet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customers
    {
        public Customers()
        {
            this.Expanses = new HashSet<Expanses>();
            this.Projects = new HashSet<Projects>();
        }
    
        public System.Guid Customer_ID { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Code { get; set; }
    
        public virtual ICollection<Expanses> Expanses { get; set; }
        public virtual ICollection<Projects> Projects { get; set; }
    }
}
