//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetAspNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpanseReports
    {
        public ExpanseReports()
        {
            this.Expanses = new HashSet<Expanses>();
        }
    
        public System.Guid ExpanseReport_ID { get; set; }
        public System.Guid Employee_ID { get; set; }
        public System.Guid Author_ID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int StatusCode { get; set; }
        public Nullable<System.DateTime> ManagerValidationDate { get; set; }
        public Nullable<System.DateTime> AccountingValidatationDate { get; set; }
        public double Total_HT { get; set; }
        public double Total_TVA { get; set; }
        public double Total_TTC { get; set; }
        public string ManagerComment { get; set; }
        public string AccountingComment { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Employees Employees1 { get; set; }
        public virtual ICollection<Expanses> Expanses { get; set; }
    }
}
