//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetAspNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expanses
    {
        public System.Guid Expanse_ID { get; set; }
        public System.Guid ExpanseReport_ID { get; set; }
        public int Day { get; set; }
        public System.Guid ExpanseType_ID { get; set; }
        public System.Guid Customer_ID { get; set; }
        public System.Guid Project_ID { get; set; }
        public double Amount_HT { get; set; }
        public double Amount_TVA { get; set; }
        public double Amount_TTC { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual ExpanseReports ExpanseReports { get; set; }
        public virtual ExpanseTypes ExpanseTypes { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
