//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetAspNet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Poles
    {
        public Poles()
        {
            this.Employees = new HashSet<Employees>();
            this.Projects = new HashSet<Projects>();
        }
    
        public Guid Pole_ID { get; set; }
        [Required]
        public string Name { get; set; }
        
        public Guid Manager_ID { get; set; }
    
        public virtual ICollection<Employees> Employees { get; set; }
        public virtual Employees Employees1 { get; set; }
        public virtual ICollection<Projects> Projects { get; set; } 
    }
}
